import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const packageRoot = path.resolve(path.dirname(__filename), "..");
const generatedDir = path.join(packageRoot, "src", "generated");
const tempBuildDir = path.join(packageRoot, ".tmp", "style-dictionary");

const aliasMap = [
  ["--color-bg", "--fd-semantic-color-background-canvas"],
  ["--color-surface", "--fd-semantic-color-surface-default"],
  ["--color-surface-strong", "--fd-semantic-color-surface-raised"],
  ["--color-surface-muted", "--fd-semantic-color-surface-muted"],
  ["--color-text", "--fd-semantic-color-text-primary"],
  ["--color-text-muted", "--fd-semantic-color-text-muted"],
  ["--color-border", "--fd-semantic-color-border-default"],
  ["--color-accent", "--fd-semantic-color-action-primary-bg"],
  ["--color-accent-strong", "--fd-semantic-color-action-primary-bg-hover"],
  ["--color-accent-foreground", "--fd-semantic-color-action-primary-fg"],
  ["--color-ring", "--fd-semantic-color-focus-ring"],
  ["--color-warning", "--fd-semantic-color-status-warning-bg"],
  ["--color-warning-foreground", "--fd-semantic-color-status-warning-fg"],
  ["--color-danger", "--fd-semantic-color-status-danger-bg"],
  ["--color-danger-foreground", "--fd-semantic-color-status-danger-fg"],
  ["--font-body", "--fd-semantic-typography-font-family-body"],
  ["--font-display", "--fd-semantic-typography-font-family-display"]
];

function runBuild(target) {
  execFileSync("pnpm", ["exec", "style-dictionary", "build", "--config", "./style-dictionary.config.mjs"], {
    cwd: packageRoot,
    stdio: "inherit",
    env: {
      ...process.env,
      FD_BUILD_TARGET: target,
      FD_OUTPUT_PATH: tempBuildDir
    }
  });
}

function readJson(filename) {
  return JSON.parse(readFileSync(path.join(tempBuildDir, filename), "utf8"));
}

function extractVariableDeclarations(cssText) {
  const variableLines = [];

  for (const match of cssText.matchAll(/^\s*(--[^:]+:\s*[^;]+;)\s*$/gm)) {
    variableLines.push(match[1]);
  }

  return Array.from(new Set(variableLines));
}

function buildAliasDeclarations(definedVariables) {
  return aliasMap.map(([legacyName, canonicalName]) => {
    if (!definedVariables.has(canonicalName)) {
      throw new Error(`Missing canonical variable ${canonicalName} required for alias ${legacyName}`);
    }

    return `${legacyName}: var(${canonicalName});`;
  });
}

function formatBlock(selector, declarations, colorScheme) {
  const definedVariables = new Set(declarations.map((line) => line.slice(0, line.indexOf(":"))));
  const aliasDeclarations = buildAliasDeclarations(definedVariables);
  const allLines = [...declarations, `color-scheme: ${colorScheme};`, ...aliasDeclarations];

  return `${selector} {\n${allLines.map((line) => `  ${line}`).join("\n")}\n}`;
}

function formatMediaBlock(selector, declarations, colorScheme) {
  const definedVariables = new Set(declarations.map((line) => line.slice(0, line.indexOf(":"))));
  const aliasDeclarations = buildAliasDeclarations(definedVariables);
  const allLines = [...declarations, `color-scheme: ${colorScheme};`, ...aliasDeclarations];

  return `@media (prefers-color-scheme: dark) {\n  ${selector} {\n${allLines.map((line) => `    ${line}`).join("\n")}\n  }\n}`;
}

function writeGeneratedFiles(baseTokens, lightTokens, darkTokens, lightCss, darkCss) {
  const lightVariables = extractVariableDeclarations(lightCss);
  const darkVariables = extractVariableDeclarations(darkCss);

  const mergedTokens = {
    base: baseTokens.base ?? baseTokens,
    themes: {
      light: {
        semantic: lightTokens.semantic ?? lightTokens
      },
      dark: {
        semantic: darkTokens.semantic ?? darkTokens
      }
    }
  };

  const css = [
    "/* This file is generated by packages/design-tokens/scripts/generate.mjs. Do not edit directly. */",
    "",
    formatBlock(":root, [data-theme=\"light\"]", lightVariables, "light"),
    "",
    formatBlock("[data-theme=\"dark\"]", darkVariables, "dark"),
    "",
    formatMediaBlock(":root:not([data-theme])", darkVariables, "dark"),
    ""
  ].join("\n");

  const json = `${JSON.stringify(mergedTokens, null, 2)}\n`;
  const js = [
    "/**",
    " * This file is generated by packages/design-tokens/scripts/generate.mjs.",
    " * Do not edit directly.",
    " */",
    `export const tokens = ${JSON.stringify(mergedTokens, null, 2)};`,
    "",
    "export default tokens;",
    ""
  ].join("\n");
  const dts = [
    "/**",
    " * This file is generated by packages/design-tokens/scripts/generate.mjs.",
    " * Do not edit directly.",
    " */",
    "export type TokenLeaf = string | number | boolean;",
    "export type TokenTree = { readonly [key: string]: TokenLeaf | TokenTree };",
    "export interface DesignTokens {",
    "  readonly base: TokenTree;",
    "  readonly themes: {",
    "    readonly light: { readonly semantic: TokenTree };",
    "    readonly dark: { readonly semantic: TokenTree };",
    "  };",
    "}",
    "export declare const tokens: DesignTokens;",
    "export default tokens;",
    ""
  ].join("\n");

  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(path.join(generatedDir, "tokens.css"), css);
  writeFileSync(path.join(generatedDir, "tokens.json"), json);
  writeFileSync(path.join(generatedDir, "tokens.js"), js);
  writeFileSync(path.join(generatedDir, "tokens.d.ts"), dts);
}

rmSync(tempBuildDir, { recursive: true, force: true });
mkdirSync(tempBuildDir, { recursive: true });

runBuild("base");
runBuild("light");
runBuild("dark");

const baseTokens = readJson("base.json");
const lightTokens = readJson("light.semantic.json");
const darkTokens = readJson("dark.semantic.json");
const lightCss = readFileSync(path.join(tempBuildDir, "light.css"), "utf8");
const darkCss = readFileSync(path.join(tempBuildDir, "dark.css"), "utf8");

writeGeneratedFiles(baseTokens, lightTokens, darkTokens, lightCss, darkCss);

rmSync(tempBuildDir, { recursive: true, force: true });
